# initial thresholds 
DICT_THRESHOLD_MONTH = {
    'id_raster_cfd.nc': [14, 'bottom'],
    'id_raster_csdi.nc': [14, 'bottom'],
    'id_raster_cwd.nc': [14, 'bottom'],
    'id_raster_dtr.nc': [14, 'bottom'],
    'id_raster_fd.nc': [14, 'bottom'],
    'id_raster_gd4.nc': [200, 'bottom'],
    'id_raster_id.nc': [14, 'bottom'],
    'id_raster_r1day.nc': [40, 'bottom'],
    'id_raster_r5day.nc': [80, 'bottom'],
    'id_raster_r95p.nc': [40, 'bottom'],
    'id_raster_r99p.nc': [25, 'bottom'],
    'id_raster_r_10mm.nc': [5, 'bottom'],
    'id_raster_r_20mm.nc': [2, 'bottom'],
    'id_raster_rr.nc': [150, 'bottom'],
    'id_raster_sdii.nc': [10, 'bottom'],
    'id_raster_su.nc': [14, 'bottom'],
    'id_raster_tg90p.nc': [14, 'bottom'],
    'id_raster_tn10p.nc': [14, 'bottom'],
    'id_raster_tn90p.nc': [14, 'bottom'],
    'id_raster_tnn.nc': [-15, 'top'],
    'id_raster_tnx.nc': [20, 'bottom'],
    'id_raster_tr.nc': [7, 'bottom'],
    'id_raster_tx10p.nc': [14, 'bottom'],
    'id_raster_tx90p.nc': [14, 'bottom'],
    'id_raster_txn.nc': [-15, 'top'],
    'id_raster_txx.nc': [35, 'bottom'],
    'id_raster_wsdi.nc': [14, 'bottom'],
    'sd_raster_spei_1.nc': [-1.5, 'top'],
    'sd_raster_spei_3.nc': [-1.5, 'top'],
    'sd_raster_spei_6.nc': [-1.5, 'top'],
    'sd_raster_spei_12.nc': [-1.5, 'top'],
    'sd_raster_spi_1.nc': [-1.5, 'top'],
    'sd_raster_spi_3.nc': [-1.5, 'top'],
    'sd_raster_spi_6.nc': [-1.5, 'top'],
    'sd_raster_spi_12.nc': [-1.5, 'top'],
    'sd_raster_sti_1.nc': [1.5, 'bottom'],
    'sd_raster_sti_3.nc': [1.5, 'bottom'],
    'sd_raster_sti_6.nc': [1.5, 'bottom'],
    'sd_raster_sti_12.nc': [1.5, 'bottom'],
}

LIST_WEEK = ['ds_raster_ET.nc',
 'ds_raster_Heat.nc',
 'ds_raster_fixed_3.nc',
 'ds_raster_fixed_4.nc',
 'ds_raster_fixed_5.nc',
 'fd_raster_alencar.nc',
 'fd_raster_ford.nc',
 'fd_raster_noguera.nc',
 'fd_raster_pendergrass.nc',
 'hw_raster_cw_1.nc',
 'hw_raster_cw_10.nc',
 'hw_raster_cw_2.nc',
 'hw_raster_cw_3.nc',
 'hw_raster_cw_7.nc',
 'hw_raster_cw_8.nc',
 'hw_raster_cw_9.nc',
 'hw_raster_hw_1.nc',
 'hw_raster_hw_10.nc',
 'hw_raster_hw_2.nc',
 'hw_raster_hw_3.nc',
 'hw_raster_hw_4.nc',
 'hw_raster_hw_6.nc',
 'hw_raster_hw_7.nc',
 'hw_raster_hw_8.nc',
 'hw_raster_hw_9.nc',
 'ws_raster_ET.nc',
 'ws_raster_Heat.nc',
 'ws_raster_fixed_1.nc',
 'ws_raster_fixed_2.nc',
 'ws_raster_fixed_5.nc']



DICT_INDEX_FILE_WEEK = {
    # daily - dry_spell
    'dry_spell_ET': 'ds_raster_ET.nc',
    'dry_spell_fixed_3': 'ds_raster_fixed_3.nc',
    'dry_spell_fixed_4': 'ds_raster_fixed_4.nc',
    'dry_spell_fixed_5': 'ds_raster_fixed_5.nc',
    # 'dry_spell_fixed_7': 'ds_raster_fixed_7.nc',
    'dry_spell_Heat': 'ds_raster_Heat.nc',
    # 'dry_spell_Storm': 'ds_raster_Storm.nc',
    # daily - flash_drought
    'flash_drought_alencar': 'fd_raster_alencar.nc',
    'flash_drought_ford': 'fd_raster_ford.nc',
    'flash_drought_noguera': 'fd_raster_noguera.nc',
    # 'flash_drought_osman': 'fd_raster_osman.nc',
    'flash_drought_pendergrass': 'fd_raster_pendergrass.nc',
    # daily - cold_wave
    'cold_wave_cw_1': 'hw_raster_cw_1.nc',
    'cold_wave_cw_2': 'hw_raster_cw_2.nc',
    'cold_wave_cw_3': 'hw_raster_cw_3.nc',
    # 'cold_wave_cw_4': 'hw_raster_cw_4.nc',
    # 'cold_wave_cw_5': 'hw_raster_cw_5.nc',
    # 'cold_wave_cw_6': 'hw_raster_cw_6.nc',
    'cold_wave_cw_7': 'hw_raster_cw_7.nc',
    'cold_wave_cw_8': 'hw_raster_cw_8.nc',
    'cold_wave_cw_9': 'hw_raster_cw_9.nc',
    'cold_wave_cw_10': 'hw_raster_cw_10.nc',
    # daily - heat_wave
    'heat_wave_hw_1': 'hw_raster_hw_1.nc',
    'heat_wave_hw_2': 'hw_raster_hw_2.nc',
    'heat_wave_hw_3': 'hw_raster_hw_3.nc',
    'heat_wave_hw_4': 'hw_raster_hw_4.nc',
    # 'heat_wave_hw_5': 'hw_raster_hw_5.nc',
    'heat_wave_hw_6': 'hw_raster_hw_6.nc',
    'heat_wave_hw_7': 'hw_raster_hw_7.nc',
    'heat_wave_hw_8': 'hw_raster_hw_8.nc',
    'heat_wave_hw_9': 'hw_raster_hw_9.nc',
    'heat_wave_hw_10': 'hw_raster_hw_10.nc',
    # daily - wet_spell
    'wet_spell_ET': 'ws_raster_ET.nc',
    'wet_spell_fixed_1': 'ws_raster_fixed_1.nc',
    'wet_spell_fixed_2': 'ws_raster_fixed_2.nc',
    'wet_spell_fixed_5': 'ws_raster_fixed_5.nc',
    'wet_spell_Heat': 'ws_raster_Heat.nc',
}

DICT_INDEX_FILE_MONTH = {
    # monthly - extreme_temperature
    'extreme_temperature_cfd': 'id_raster_cfd.nc',
    'extreme_temperature_csdi': 'id_raster_csdi.nc',
    'extreme_temperature_dtr': 'id_raster_dtr.nc',
    'extreme_temperature_fd': 'id_raster_fd.nc',
    'extreme_temperature_gd4': 'id_raster_gd4.nc',
    'extreme_temperature_id': 'id_raster_id.nc',
    'extreme_temperature_su': 'id_raster_su.nc',
    'extreme_temperature_tg90p': 'id_raster_tg90p.nc',
    'extreme_temperature_tn10p': 'id_raster_tn10p.nc',
    'extreme_temperature_tn90p': 'id_raster_tn90p.nc',
    'extreme_temperature_tnn': 'id_raster_tnn.nc',
    'extreme_temperature_tnx': 'id_raster_tnx.nc',
    'extreme_temperature_tr': 'id_raster_tr.nc',
    'extreme_temperature_tx10p': 'id_raster_tx10p.nc',
    'extreme_temperature_tx90p': 'id_raster_tx90p.nc',
    'extreme_temperature_txn': 'id_raster_txn.nc',
    'extreme_temperature_txx': 'id_raster_txx.nc',
    'extreme_temperature_wsdi': 'id_raster_wsdi.nc',
    # monthly - extreme_precipitation
    'extreme_precipitation_cwd': 'id_raster_cwd.nc',
    'extreme_precipitation_r_10mm': 'id_raster_r_10mm.nc',
    'extreme_precipitation_r_20mm': 'id_raster_r_20mm.nc',
    'extreme_precipitation_r1day': 'id_raster_r1day.nc',
    'extreme_precipitation_r5day': 'id_raster_r5day.nc',
    'extreme_precipitation_r95p': 'id_raster_r95p.nc',
    'extreme_precipitation_r99p': 'id_raster_r99p.nc',
    'extreme_precipitation_rr': 'id_raster_rr.nc',
    'extreme_precipitation_sdii': 'id_raster_sdii.nc',
    # monthly - standard_drought
    'standard_drought_spei_1': 'sd_raster_spei_1.nc',
    'standard_drought_spei_3': 'sd_raster_spei_3.nc',
    'standard_drought_spei_6': 'sd_raster_spei_6.nc',
    'standard_drought_spei_12': 'sd_raster_spei_12.nc',
    'standard_drought_spi_1': 'sd_raster_spi_1.nc',
    'standard_drought_spi_3': 'sd_raster_spi_3.nc',
    'standard_drought_spi_6': 'sd_raster_spi_6.nc',
    'standard_drought_spi_12': 'sd_raster_spi_12.nc',
    'standard_drought_sti_1': 'sd_raster_sti_1.nc',
    'standard_drought_sti_3': 'sd_raster_sti_3.nc',
    'standard_drought_sti_6': 'sd_raster_sti_6.nc',
    'standard_drought_sti_12': 'sd_raster_sti_12.nc',
}