# initial thresholds 
DICT_THRESHOLD_MONTH = {
    'id_raster_cfd.nc': [14, 'bottom'],
    'id_raster_csdi.nc': [14, 'bottom'],
    'id_raster_cwd.nc': [14, 'bottom'],
    'id_raster_dtr.nc': [14, 'bottom'],
    'id_raster_fd.nc': [14, 'bottom'],
    'id_raster_gd4.nc': [200, 'bottom'],
    'id_raster_id.nc': [14, 'bottom'],
    'id_raster_r1day.nc': [40, 'bottom'],
    'id_raster_r5day.nc': [80, 'bottom'],
    'id_raster_r95p.nc': [40, 'bottom'],
    'id_raster_r99p.nc': [25, 'bottom'],
    'id_raster_r_10mm.nc': [5, 'bottom'],
    'id_raster_r_20mm.nc': [2, 'bottom'],
    'id_raster_rr.nc': [150, 'bottom'],
    'id_raster_sdii.nc': [10, 'bottom'],
    'id_raster_su.nc': [14, 'bottom'],
    'id_raster_tg90p.nc': [14, 'bottom'],
    'id_raster_tn10p.nc': [14, 'bottom'],
    'id_raster_tn90p.nc': [14, 'bottom'],
    'id_raster_tnn.nc': [-15, 'top'],
    'id_raster_tnx.nc': [20, 'bottom'],
    'id_raster_tr.nc': [7, 'bottom'],
    'id_raster_tx10p.nc': [14, 'bottom'],
    'id_raster_tx90p.nc': [14, 'bottom'],
    'id_raster_txn.nc': [-15, 'top'],
    'id_raster_txx.nc': [35, 'bottom'],
    'id_raster_wsdi.nc': [14, 'bottom'],
    'sd_raster_spei_1.nc': [-1.5, 'top'],
    'sd_raster_spei_3.nc': [-1.5, 'top'],
    'sd_raster_spei_6.nc': [-1.5, 'top'],
    'sd_raster_spei_12.nc': [-1.5, 'top'],
    'sd_raster_spi_1.nc': [-1.5, 'top'],
    'sd_raster_spi_3.nc': [-1.5, 'top'],
    'sd_raster_spi_6.nc': [-1.5, 'top'],
    'sd_raster_spi_12.nc': [-1.5, 'top'],
    'sd_raster_sti_1.nc': [1.5, 'bottom'],
    'sd_raster_sti_3.nc': [1.5, 'bottom'],
    'sd_raster_sti_6.nc': [1.5, 'bottom'],
    'sd_raster_sti_12.nc': [1.5, 'bottom'],
}

LIST_WEEK = ['ds_raster_ET.nc',
 'ds_raster_Heat.nc',
 'ds_raster_fixed_3.nc',
 'ds_raster_fixed_4.nc',
 'ds_raster_fixed_5.nc',
 'fd_raster_alencar.nc',
 'fd_raster_ford.nc',
 'fd_raster_noguera.nc',
 'fd_raster_pendergrass.nc',
 'hw_raster_cw_1.nc',
 'hw_raster_cw_10.nc',
 'hw_raster_cw_2.nc',
 'hw_raster_cw_3.nc',
 'hw_raster_cw_7.nc',
 'hw_raster_cw_8.nc',
 'hw_raster_cw_9.nc',
 'hw_raster_hw_1.nc',
 'hw_raster_hw_10.nc',
 'hw_raster_hw_2.nc',
 'hw_raster_hw_3.nc',
 'hw_raster_hw_4.nc',
 'hw_raster_hw_6.nc',
 'hw_raster_hw_7.nc',
 'hw_raster_hw_8.nc',
 'hw_raster_hw_9.nc',
 'ws_raster_ET.nc',
 'ws_raster_Heat.nc',
 'ws_raster_fixed_1.nc',
 'ws_raster_fixed_2.nc',
 'ws_raster_fixed_5.nc']